# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: ubuntu_16_04
  displayName: 'Build - Ubuntu 16.04'
  continueOnError: false
  pool:
    vmImage: 'Ubuntu 16.04'
  workspace:
    clean: all
  steps:
    - task: CMake@1
      inputs:
      cmakeArgs: 
    - script: |
        cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DOATPP_INSTALL=OFF -DOATPP_BUILD_TESTS=ON
        make
      displayName: 'CMake'

    - script: |
        make test ARGS="-V"
      displayName: 'Test'

##- job: macOS
##  displayName: 'Build - macOS-10.13'
##  continueOnError: false
##  pool:
##    vmImage: 'macOS-10.13'
