# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: ubuntu_16_04
  displayName: 'Build - Ubuntu 16.04'
  continueOnError: false
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      ubuntu14:
        containerImage: ubuntu:14.04
      ubuntu16:
        containerImage: ubuntu:16.04
      ubuntu18:
        containerImage: ubuntu:18.04

  container: $[ variables['containerImage'] ]
  
  workspace:
    clean: all
  steps:
    - script: |
        mkdir build
    - task: CMake@1
    - script: |
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DOATPP_INSTALL=OFF -DOATPP_BUILD_TESTS=ON ..
        make
      displayName: 'CMake'
      workingDirectory: build

    - script: |
        make test ARGS="-V"
      displayName: 'Test'
      workingDirectory: build

- job: macOS
  displayName: 'Build - macOS-10.13'
  continueOnError: false
  pool:
    vmImage: 'macOS-10.13'
  workspace:
    clean: all
  steps:
    - script: |
        mkdir build
    - task: CMake@1
    - script: |
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DOATPP_INSTALL=OFF -DOATPP_BUILD_TESTS=ON ..
        make
      displayName: 'CMake'
      workingDirectory: build

    - script: |
        make test ARGS="-V"
      displayName: 'Test'
      workingDirectory: build
